// <auto-generated />
using System;
using MedManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedManager.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424074850_Phase4_PushSubscriptions")]
    partial class Phase4_PushSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MedManager.Api.Domain.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpenedShelfLifeDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strength")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ExpiryDate");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("MedManager.Api.Domain.MedicineUseCase", b =>
                {
                    b.Property<Guid>("MedicineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UseCaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("MedicineId", "UseCaseId");

                    b.HasIndex("UseCaseId");

                    b.ToTable("MedicineUseCases");
                });

            modelBuilder.Entity("MedManager.Api.Domain.PushSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("MedManager.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MedManager.Api.Domain.UseCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icd10Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("UseCases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            Icd10Code = "R51",
                            NameEn = "Headache",
                            NameTr = "Baş ağrısı",
                            Slug = "headache"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            Icd10Code = "G43",
                            NameEn = "Migraine",
                            NameTr = "Migren",
                            Slug = "migraine"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            Icd10Code = "R50",
                            NameEn = "Fever",
                            NameTr = "Ateş",
                            Slug = "fever"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            Icd10Code = "J02",
                            NameEn = "Sore throat",
                            NameTr = "Boğaz ağrısı",
                            Slug = "sore-throat"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000000"),
                            Icd10Code = "J00",
                            NameEn = "Common cold",
                            NameTr = "Nezle",
                            Slug = "common-cold"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000000"),
                            Icd10Code = "J11",
                            NameEn = "Flu",
                            NameTr = "Grip",
                            Slug = "flu"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000000"),
                            Icd10Code = "R05",
                            NameEn = "Cough",
                            NameTr = "Öksürük",
                            Slug = "cough"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000000"),
                            Icd10Code = "J34",
                            NameEn = "Runny nose",
                            NameTr = "Burun akıntısı",
                            Slug = "runny-nose"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000000"),
                            Icd10Code = "R09",
                            NameEn = "Nasal congestion",
                            NameTr = "Burun tıkanıklığı",
                            Slug = "nasal-congestion"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-000000000000"),
                            Icd10Code = "J32",
                            NameEn = "Sinusitis",
                            NameTr = "Sinüzit",
                            Slug = "sinusitis"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000000"),
                            Icd10Code = "H66",
                            NameEn = "Ear infection",
                            NameTr = "Kulak iltihabı",
                            Slug = "otitis"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0000-0000-0000-000000000000"),
                            Icd10Code = "R11",
                            NameEn = "Nausea",
                            NameTr = "Mide bulantısı",
                            Slug = "nausea"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0000-0000-0000-000000000000"),
                            Icd10Code = "R11",
                            NameEn = "Vomiting",
                            NameTr = "Kusma",
                            Slug = "vomiting"
                        },
                        new
                        {
                            Id = new Guid("0000000e-0000-0000-0000-000000000000"),
                            Icd10Code = "K52",
                            NameEn = "Diarrhea",
                            NameTr = "İshal",
                            Slug = "diarrhea"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0000-0000-0000-000000000000"),
                            Icd10Code = "K59",
                            NameEn = "Constipation",
                            NameTr = "Kabızlık",
                            Slug = "constipation"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000000"),
                            Icd10Code = "R10",
                            NameEn = "Stomach pain",
                            NameTr = "Mide ağrısı",
                            Slug = "stomach-pain"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000000"),
                            Icd10Code = "K30",
                            NameEn = "Indigestion",
                            NameTr = "Hazımsızlık",
                            Slug = "indigestion"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000000"),
                            Icd10Code = "R12",
                            NameEn = "Heartburn",
                            NameTr = "Mide ekşimesi",
                            Slug = "heartburn"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000000"),
                            Icd10Code = "K29",
                            NameEn = "Gastritis",
                            NameTr = "Gastrit",
                            Slug = "gastritis"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000000"),
                            Icd10Code = "K21",
                            NameEn = "Reflux",
                            NameTr = "Reflü",
                            Slug = "reflux"
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000000"),
                            Icd10Code = "T78",
                            NameEn = "Allergy",
                            NameTr = "Alerji",
                            Slug = "allergy"
                        },
                        new
                        {
                            Id = new Guid("00000016-0000-0000-0000-000000000000"),
                            Icd10Code = "J30",
                            NameEn = "Hay fever",
                            NameTr = "Saman nezlesi",
                            Slug = "hay-fever"
                        },
                        new
                        {
                            Id = new Guid("00000017-0000-0000-0000-000000000000"),
                            Icd10Code = "J45",
                            NameEn = "Asthma",
                            NameTr = "Astım",
                            Slug = "asthma"
                        },
                        new
                        {
                            Id = new Guid("00000018-0000-0000-0000-000000000000"),
                            Icd10Code = "R21",
                            NameEn = "Skin rash",
                            NameTr = "Cilt döküntüsü",
                            Slug = "skin-rash"
                        },
                        new
                        {
                            Id = new Guid("00000019-0000-0000-0000-000000000000"),
                            Icd10Code = "L29",
                            NameEn = "Itching",
                            NameTr = "Kaşıntı",
                            Slug = "itching"
                        },
                        new
                        {
                            Id = new Guid("0000001a-0000-0000-0000-000000000000"),
                            Icd10Code = "L30",
                            NameEn = "Eczema",
                            NameTr = "Egzama",
                            Slug = "eczema"
                        },
                        new
                        {
                            Id = new Guid("0000001b-0000-0000-0000-000000000000"),
                            Icd10Code = "L70",
                            NameEn = "Acne",
                            NameTr = "Akne",
                            Slug = "acne"
                        },
                        new
                        {
                            Id = new Guid("0000001c-0000-0000-0000-000000000000"),
                            Icd10Code = "B35",
                            NameEn = "Fungal infection",
                            NameTr = "Mantar enfeksiyonu",
                            Slug = "fungal-infection"
                        },
                        new
                        {
                            Id = new Guid("0000001d-0000-0000-0000-000000000000"),
                            NameEn = "Wound care",
                            NameTr = "Yara bakımı",
                            Slug = "wound-care"
                        },
                        new
                        {
                            Id = new Guid("0000001e-0000-0000-0000-000000000000"),
                            Icd10Code = "T14",
                            NameEn = "Insect bite",
                            NameTr = "Böcek ısırığı",
                            Slug = "insect-bite"
                        },
                        new
                        {
                            Id = new Guid("0000001f-0000-0000-0000-000000000000"),
                            Icd10Code = "L55",
                            NameEn = "Sunburn",
                            NameTr = "Güneş yanığı",
                            Slug = "sunburn"
                        },
                        new
                        {
                            Id = new Guid("00000020-0000-0000-0000-000000000000"),
                            Icd10Code = "M54",
                            NameEn = "Back pain",
                            NameTr = "Bel ağrısı",
                            Slug = "back-pain"
                        },
                        new
                        {
                            Id = new Guid("00000021-0000-0000-0000-000000000000"),
                            Icd10Code = "M79",
                            NameEn = "Muscle pain",
                            NameTr = "Kas ağrısı",
                            Slug = "muscle-pain"
                        },
                        new
                        {
                            Id = new Guid("00000022-0000-0000-0000-000000000000"),
                            Icd10Code = "M25",
                            NameEn = "Joint pain",
                            NameTr = "Eklem ağrısı",
                            Slug = "joint-pain"
                        },
                        new
                        {
                            Id = new Guid("00000023-0000-0000-0000-000000000000"),
                            Icd10Code = "M19",
                            NameEn = "Arthritis",
                            NameTr = "Artrit",
                            Slug = "arthritis"
                        },
                        new
                        {
                            Id = new Guid("00000024-0000-0000-0000-000000000000"),
                            Icd10Code = "N94",
                            NameEn = "Menstrual pain",
                            NameTr = "Adet ağrısı",
                            Slug = "menstrual-pain"
                        },
                        new
                        {
                            Id = new Guid("00000025-0000-0000-0000-000000000000"),
                            Icd10Code = "G47",
                            NameEn = "Insomnia",
                            NameTr = "Uykusuzluk",
                            Slug = "insomnia"
                        },
                        new
                        {
                            Id = new Guid("00000026-0000-0000-0000-000000000000"),
                            Icd10Code = "F41",
                            NameEn = "Anxiety",
                            NameTr = "Anksiyete",
                            Slug = "anxiety"
                        },
                        new
                        {
                            Id = new Guid("00000027-0000-0000-0000-000000000000"),
                            Icd10Code = "I10",
                            NameEn = "Hypertension",
                            NameTr = "Yüksek tansiyon",
                            Slug = "hypertension"
                        },
                        new
                        {
                            Id = new Guid("00000028-0000-0000-0000-000000000000"),
                            Icd10Code = "I95",
                            NameEn = "Low blood pressure",
                            NameTr = "Düşük tansiyon",
                            Slug = "hypotension"
                        },
                        new
                        {
                            Id = new Guid("00000029-0000-0000-0000-000000000000"),
                            Icd10Code = "E11",
                            NameEn = "Diabetes",
                            NameTr = "Diyabet",
                            Slug = "diabetes"
                        },
                        new
                        {
                            Id = new Guid("0000002a-0000-0000-0000-000000000000"),
                            Icd10Code = "E78",
                            NameEn = "High cholesterol",
                            NameTr = "Yüksek kolesterol",
                            Slug = "high-cholesterol"
                        },
                        new
                        {
                            Id = new Guid("0000002b-0000-0000-0000-000000000000"),
                            Icd10Code = "H04",
                            NameEn = "Dry eyes",
                            NameTr = "Göz kuruluğu",
                            Slug = "dry-eyes"
                        },
                        new
                        {
                            Id = new Guid("0000002c-0000-0000-0000-000000000000"),
                            Icd10Code = "H10",
                            NameEn = "Conjunctivitis",
                            NameTr = "Konjonktivit",
                            Slug = "conjunctivitis"
                        },
                        new
                        {
                            Id = new Guid("0000002d-0000-0000-0000-000000000000"),
                            Icd10Code = "K08",
                            NameEn = "Toothache",
                            NameTr = "Diş ağrısı",
                            Slug = "toothache"
                        },
                        new
                        {
                            Id = new Guid("0000002e-0000-0000-0000-000000000000"),
                            Icd10Code = "K12",
                            NameEn = "Mouth ulcer",
                            NameTr = "Ağız içi yarası",
                            Slug = "mouth-ulcer"
                        },
                        new
                        {
                            Id = new Guid("0000002f-0000-0000-0000-000000000000"),
                            Icd10Code = "N39",
                            NameEn = "Urinary tract infection",
                            NameTr = "İdrar yolu enfeksiyonu",
                            Slug = "urinary-tract"
                        },
                        new
                        {
                            Id = new Guid("00000030-0000-0000-0000-000000000000"),
                            Icd10Code = "E56",
                            NameEn = "Vitamin deficiency",
                            NameTr = "Vitamin eksikliği",
                            Slug = "vitamin-deficiency"
                        },
                        new
                        {
                            Id = new Guid("00000031-0000-0000-0000-000000000000"),
                            Icd10Code = "D64",
                            NameEn = "Anemia",
                            NameTr = "Anemi",
                            Slug = "anemia"
                        },
                        new
                        {
                            Id = new Guid("00000032-0000-0000-0000-000000000000"),
                            Icd10Code = "T75",
                            NameEn = "Motion sickness",
                            NameTr = "Taşıt tutması",
                            Slug = "motion-sickness"
                        });
                });

            modelBuilder.Entity("MedManager.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedManager.Api.Domain.Medicine", b =>
                {
                    b.HasOne("MedManager.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedManager.Api.Domain.MedicineUseCase", b =>
                {
                    b.HasOne("MedManager.Api.Domain.Medicine", "Medicine")
                        .WithMany("UseCases")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedManager.Api.Domain.UseCase", "UseCase")
                        .WithMany("Medicines")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("UseCase");
                });

            modelBuilder.Entity("MedManager.Api.Domain.PushSubscriptionEntity", b =>
                {
                    b.HasOne("MedManager.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedManager.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("MedManager.Api.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedManager.Api.Domain.Medicine", b =>
                {
                    b.Navigation("UseCases");
                });

            modelBuilder.Entity("MedManager.Api.Domain.UseCase", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedManager.Api.Domain.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
