import { db } from "./client.js";
import { useCases } from "./schema.js";

const CATALOG: readonly { slug: string; nameTr: string; nameEn: string; icd10Code?: string }[] = [
  { slug: "headache", nameTr: "Baş ağrısı", nameEn: "Headache", icd10Code: "R51" },
  { slug: "migraine", nameTr: "Migren", nameEn: "Migraine", icd10Code: "G43" },
  { slug: "fever", nameTr: "Ateş", nameEn: "Fever", icd10Code: "R50" },
  { slug: "sore-throat", nameTr: "Boğaz ağrısı", nameEn: "Sore throat", icd10Code: "J02" },
  { slug: "common-cold", nameTr: "Nezle", nameEn: "Common cold", icd10Code: "J00" },
  { slug: "flu", nameTr: "Grip", nameEn: "Flu", icd10Code: "J11" },
  { slug: "cough", nameTr: "Öksürük", nameEn: "Cough", icd10Code: "R05" },
  { slug: "runny-nose", nameTr: "Burun akıntısı", nameEn: "Runny nose", icd10Code: "J34" },
  { slug: "nasal-congestion", nameTr: "Burun tıkanıklığı", nameEn: "Nasal congestion", icd10Code: "R09" },
  { slug: "sinusitis", nameTr: "Sinüzit", nameEn: "Sinusitis", icd10Code: "J32" },
  { slug: "otitis", nameTr: "Kulak iltihabı", nameEn: "Ear infection", icd10Code: "H66" },
  { slug: "nausea", nameTr: "Mide bulantısı", nameEn: "Nausea", icd10Code: "R11" },
  { slug: "vomiting", nameTr: "Kusma", nameEn: "Vomiting", icd10Code: "R11" },
  { slug: "diarrhea", nameTr: "İshal", nameEn: "Diarrhea", icd10Code: "K52" },
  { slug: "constipation", nameTr: "Kabızlık", nameEn: "Constipation", icd10Code: "K59" },
  { slug: "stomach-pain", nameTr: "Mide ağrısı", nameEn: "Stomach pain", icd10Code: "R10" },
  { slug: "indigestion", nameTr: "Hazımsızlık", nameEn: "Indigestion", icd10Code: "K30" },
  { slug: "heartburn", nameTr: "Mide ekşimesi", nameEn: "Heartburn", icd10Code: "R12" },
  { slug: "gastritis", nameTr: "Gastrit", nameEn: "Gastritis", icd10Code: "K29" },
  { slug: "reflux", nameTr: "Reflü", nameEn: "Reflux", icd10Code: "K21" },
  { slug: "allergy", nameTr: "Alerji", nameEn: "Allergy", icd10Code: "T78" },
  { slug: "hay-fever", nameTr: "Saman nezlesi", nameEn: "Hay fever", icd10Code: "J30" },
  { slug: "asthma", nameTr: "Astım", nameEn: "Asthma", icd10Code: "J45" },
  { slug: "skin-rash", nameTr: "Cilt döküntüsü", nameEn: "Skin rash", icd10Code: "R21" },
  { slug: "itching", nameTr: "Kaşıntı", nameEn: "Itching", icd10Code: "L29" },
  { slug: "eczema", nameTr: "Egzama", nameEn: "Eczema", icd10Code: "L30" },
  { slug: "acne", nameTr: "Akne", nameEn: "Acne", icd10Code: "L70" },
  { slug: "fungal-infection", nameTr: "Mantar enfeksiyonu", nameEn: "Fungal infection", icd10Code: "B35" },
  { slug: "wound-care", nameTr: "Yara bakımı", nameEn: "Wound care" },
  { slug: "insect-bite", nameTr: "Böcek ısırığı", nameEn: "Insect bite", icd10Code: "T14" },
  { slug: "sunburn", nameTr: "Güneş yanığı", nameEn: "Sunburn", icd10Code: "L55" },
  { slug: "back-pain", nameTr: "Bel ağrısı", nameEn: "Back pain", icd10Code: "M54" },
  { slug: "muscle-pain", nameTr: "Kas ağrısı", nameEn: "Muscle pain", icd10Code: "M79" },
  { slug: "joint-pain", nameTr: "Eklem ağrısı", nameEn: "Joint pain", icd10Code: "M25" },
  { slug: "arthritis", nameTr: "Artrit", nameEn: "Arthritis", icd10Code: "M19" },
  { slug: "menstrual-pain", nameTr: "Adet ağrısı", nameEn: "Menstrual pain", icd10Code: "N94" },
  { slug: "insomnia", nameTr: "Uykusuzluk", nameEn: "Insomnia", icd10Code: "G47" },
  { slug: "anxiety", nameTr: "Anksiyete", nameEn: "Anxiety", icd10Code: "F41" },
  { slug: "hypertension", nameTr: "Yüksek tansiyon", nameEn: "Hypertension", icd10Code: "I10" },
  { slug: "hypotension", nameTr: "Düşük tansiyon", nameEn: "Low blood pressure", icd10Code: "I95" },
  { slug: "diabetes", nameTr: "Diyabet", nameEn: "Diabetes", icd10Code: "E11" },
  { slug: "high-cholesterol", nameTr: "Yüksek kolesterol", nameEn: "High cholesterol", icd10Code: "E78" },
  { slug: "dry-eyes", nameTr: "Göz kuruluğu", nameEn: "Dry eyes", icd10Code: "H04" },
  { slug: "conjunctivitis", nameTr: "Konjonktivit", nameEn: "Conjunctivitis", icd10Code: "H10" },
  { slug: "toothache", nameTr: "Diş ağrısı", nameEn: "Toothache", icd10Code: "K08" },
  { slug: "mouth-ulcer", nameTr: "Ağız içi yarası", nameEn: "Mouth ulcer", icd10Code: "K12" },
  { slug: "urinary-tract", nameTr: "İdrar yolu enfeksiyonu", nameEn: "Urinary tract infection", icd10Code: "N39" },
  { slug: "vitamin-deficiency", nameTr: "Vitamin eksikliği", nameEn: "Vitamin deficiency", icd10Code: "E56" },
  { slug: "anemia", nameTr: "Anemi", nameEn: "Anemia", icd10Code: "D64" },
  { slug: "motion-sickness", nameTr: "Taşıt tutması", nameEn: "Motion sickness", icd10Code: "T75" },
];

export async function seedUseCases(): Promise<void> {
  for (const c of CATALOG) {
    await db.insert(useCases).values({ ...c, userId: null }).onConflictDoNothing();
  }
}
